### ISSUE TITLE
Insufficient parameters for a scalar (1-D) response vector; non-conforming P and Z?

### ISSUE THREAD

**Issue by ghost** [DylanB95/statespacer#4]
Hello.  I am exploring using statespacer for a case where I want to estimate both the observation variance and the state space variance-covariance. I am getting a couple of messages:

`Browse[1]> c
Error in P %*% t(Z) : non-conformable arguments
optim method failure
Finished the optimisation procedure at: 2020-05-29 18:36:59
Time difference of 1.64809393882751 secs

Error in Cholesky(param = param[param_indices$H], format = H_format, decompositions = TRUE) : 
  Not enough parameters supplied.
> 
`

The setup and call is:

`  # Setup
  #
  #           [     x_{t}             ] 
  #  theta :  [  \od{x}{t}            ]
  #           [  \od[2]{x}{t}         ]
  #
  self_spec_list<- list()
  #
  # 1 parameter for sigma^2
  # 6 for variance-covariance matrix Sigma_eta, or Q
  #
  self_spec_list$H_spec<- FALSE
  self_spec_list$P_inf<- matrix(0, 3, 3)
  self_spec_list$P_star<- diag(3)
  self_spec_list$Z<- matrix(c(1,0,0), nrow=1, ncol=3)
  self_spec_list$Tmat<- matrix(c(1,1,0,0,1,1,0,0,0), nrow=3, ncol=3, byrow=TRUE)
  self_spec_list$R<- diag(3)
  self_spec_list$a1<- matrix(0, nrow=3, ncol=1)
  self_spec_list$param_num<- 7
  self_spec_list$state_only<- 2:7
  self_spec_list$state_num<- 6
  self_spec_list$sys_mat_fun<- function(param)
    {
      ChoD<- Cholesky(param=param[2:7], decompositions=TRUE, format=matrix(1,3,3))
      Q<- ChoD$cov_mat
      sigma2<- exp(2*param[1])
      H<- sigma2*diag(1)
      cat("sys_mat_fun:\n")
      browser()
      return(list(Q=Q, H=H))
    }
  #
  inits<- runif(7)
  if (debug)
  {
    ctrl<- list(trace=4)
  } else
  {
    ctrl<- list()
  }
  #
  fit<- StateSpaceFit(y=S.scaled, self_spec_list=self_spec_list, collapse=FALSE, 
                      initial=inits, method="L-BFGS-B", control=ctrl, H_format=matrix(1,1,1))
  #
`
Sorry to trouble you but I've wandered about in the code from the Github trying to figure out what's wrong here, and I can't figure it out. 

I'm assuming the matrices in the model need to be conformable. My process transition matrix T is 3x3, so T == [1, 1, 0 \\ 0, 1, 0 \\ 0, 0, 0], The state is 3x1, so I'm assuming Z is [1, 0, 0] rather than [1 \\ 0 \\ 0]. I'm specifying H as 1x1 and its format as matrix(1,1,1). I devote 1 parameter to the observation and 6 to the process covariance estimation. 

Thoughts?

**Comment by DylanB95** [comment]
Hi, 

I've encountered this error a few times while writing the vignettes, and all of those times what was really going wrong is `optim` returning NAs as optimal parameters. This is due to the failure of the optimisation procedure, so you probably need to try different initial values. Just now, I've built in an error handler for checking if `optim` returns NAs, so the real problem doesn't get obscured anymore by "non-conformable arguments". (This "non-conformable arguments" error happens because the optimal parameters are passed on to calculate the components, during which the NAs are eliminated, thus resulting in faulty matrices.)

Further, there are some errors with the specification of self_spec_list:

- You specify self_spec_list$H_spec<- FALSE, while you actually do specify H yourself. So you should set self_spec_list$H_spec to TRUE. In this case, I'd prefer eliminating the H from self_spec_list$sys_mat_fun and leave self_spec_list$H_spec to FALSE, as `StateSpaceFit` is able to compute H by itself as exp(2*param[1]), so there's no need to specify it yourself.

- You specify self_spec_list$P_star<- diag(3). This is not necessarily wrong for the method to work, but I think it is mathematically wrong. P_star is used as the initial variance-covariance matrix for the state vector. When the state vector is stationary, this matrix can be calculated exactly. See https://dylanb95.github.io/statespacer/articles/selfspec.html for an example how to calculate this matrix exactly using the T, R and Q system matrices. In case the state vector is not stationary, you'd want to use a diffuse initialisation. This can be done by setting self_spec_list$P_inf<- diag(3) and self_spec_list$P_star<- matrix(0, 3, 3).

- You specified self_spec_list$state_num<- 6. This should be self_spec_list$state_num<- 3, as the state vector has length 3 (the length of a1). state_num refers to the number of elements in the state vector as introduced by the self specified component, not to the number of parameters (that are optimised over by the optimisation procedure). You don't have to specify self_spec_list$state_only as you set collapse = FALSE (it doesn't hurt either as it's simply ignored in this case).

When I look at the system matrices you've defined, it looks really similar (basically identical apart from the extra error term you've put in the state vector as the 3rd element) to a local level + trend model. Is that actually what you are trying to fit? In this case you could save a lot of work, as the local level + trend is a built in option. You simply would have to specify slope_ind = TRUE in your call to `StateSpaceFit`. For example, fit <- StateSpaceFit(y = S.scaled, slope_ind = TRUE, initial=inits) would be sufficient. If you do actually want to estimate a correlation between the level disturbance and the slope disturbance, you would have to make use of self_spec_list though.

Let me know if this solves your problem, I'm happy to help! :)

**Comment by ghost** [comment]
Thank you _so_ much for your hints.  Actually, for the application at hand, I'm keenly interested in estimating the variances of the first and second derivatives, and everything else is part of the mechanism. 

I also want to learn how to use _statespacer_.  I have a lot of experience using _dlm_. This is a case.

I am writing a blog post, not yet out there, relating to COVID_19 and [an earlier post](https://667-per-cm.net/2020/05/02/phase-plane-plots-of-covid-19-deaths/).  I'll specifically mention the _statespacer_ application there.

**Comment by DylanB95** [comment]
That looks interesting, I'll take a closer look at the blog post tomorrow. I'll close this issue now, but feel free to contact me directly by emailing me, and keeping me posted about your next blog! Hopefully you got it working with the initial values, it can be a bit of trial and error to find proper starting points.
